version: 2.1

orbs:
  node: circleci/node@5.0.0

executors:
  node-executor:
    docker:
      - image: cimg/node:20.6-browsers

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node Modules
          command: npm ci --legacy-peer-deps
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package-lock.json

  run-tests:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm test

  build-backend:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Backend
          command: npm run build

workflows:
  build-and-test:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
      - build-backend:
          requires:
            - run-tests